### ISSUE TITLE
ConfigUtil.getOptionalDuration changes time unit

### ISSUE THREAD

**Issue by anilgursel** [paypal/squbs#140]
`ConfigUtil.getOptionalDuration` should keep the time unit.

**Comment by akara** [comment]
Sorry, we need the new version of Typesafe config and therefore Akka 2.4 to have the right getDuration signature retaining the time unit. This cannot be implemented with Akka 2.3.X

**Comment by anilgursel** [comment]
`scala.concurrent.duration.Duration` has `length` and `unit` methods; however, `java.time.Duration` does not.  So, it gets problematic and requires a complicated logic, which is probably not worth it.

Please see https://github.com/typesafehub/config/issues/165.

**Comment by akara** [comment]
I'd make a few changes to ConfigUtil to solve this issue, as follows:

```scala
private val DurationTag = typeTag[Duration]
private val FiniteDurationTag = typeTag[FiniteDuration]

...
case DurationTag => Some(Duration(underlying.getString(path))
case FiniteDurationTag => Some(Duration(underlying.getString(path)).asInstanceOf[FiniteDuration])
```

Then we have to add tests to test the finite case and the infinite case. The infinite case should throw a ClassCastException.

**Comment by akara** [comment]
This means we're not going through the `getDuration` signature at all and still achieve the desired results. Please let me know what you think.

**Comment by dmartyanov** [comment]
@akara this approach looks good to me,  we don't have to use `getDuration` signature if it loses some data.
I have only one concern about `ClassCastException` for infinite case, because essentially it is not a failure of upcast,  it is string value that doesn't correspond to  any value from the set of permissible values defined by `FiniteDuration` type. We can return just `None` as for any other incorrect string.
In general I suppose that `getOption[T]` shouldn't throw exceptions if it's used properly, as it were done in `getOptionalString` and other methods.

**Comment by akara** [comment]
Good point. Let's check before casting or catch the exception. Thanks!

**Comment by dmartyanov** [comment]
If we need to inject more type cast logic into `RichConfig` I would like to suggest the following:
Extract method `getTry[T]: Try[T]` and implement all the logic of fetching config values and type casting with proper exceptions handling.  Execute `getTry[T]` inside `getOption[T]` and divide all the exceptions into 2 groups for Failure case: 
1. Exceptions of data in config and it's representation, they should be recovered with None
2. Exceptions of incorrect method call,  like `IllegalArgumentException`,  they should be thrown downstream

**Comment by akara** [comment]
This approach looks good to me. In addition, I think in case of `getOption` returning `None` because of a formatting issue, we should log such issues at level `WARN`.

**Comment by dmartyanov** [comment]
Agree
