### ISSUE TITLE
squbsconfig is not in the classpath

### ISSUE THREAD

**Issue by thefourtheye** [paypal/squbs#163]
I have a module, lets say "Module-1", which tries to load a config file from resources using `getClass.getResourceAsStream`, but the file is not part of this module itself, it comes from a different module. When I start the application, squbs copies all those configuration files to `squbsconfig` directory, but doesn't include that in the classpath. So, at runtime, "Module-1" fails to load the file.

As of now, I am using
```scala
unmanagedClasspath in Runtime <+= (baseDirectory) map { bd => Attributed.blank(bd / "squbsconfig") }
```
in the `build.sbt` file to get around the problem. I feel that this should have been done by squbs itself.

**Comment by akara** [comment]
@thefourtheye: squbs by itself does not make any such copy. But the extensions used by ebay/paypal do. Still, squbsconfig was never intended to be part of the classpath. You can load a config from the filesystem directly, too. It seems your experience is with ebay or paypal extensions. In such cases, please do reach out directly on the support channels of the appropriate organization and we'll specifically look at your use case. Let me know if you don't know these.

**Comment by thefourtheye** [comment]
@akara Cool. Thanks. I'll send an E-Mail.
