### ISSUE TITLE
Test RouteDefinition in squbs

### ISSUE THREAD

**Issue by elong408** [paypal/squbs#18]
As today, if we want to test RouteDefinition using spray-testkit, we need to add some workaround to create the route instance.

e.g.

val actor = TestActorRef[DummyActor]

val route = RouteDefinition
  .startRoutes(new SellercommunitysvcSvc)(actor.underlyingActor.context).route
class DummyActor extends Actor {
  override def receive: Receive = {
    case whatever =>
  }
}

Then apply the route assertion like:

REQUEST ~> route ~> check {
  ASSERTIONS
}

**Comment by akara** [comment]
Please review and comment on PR https://github.com/paypal/squbs/pull/33

**Comment by akara** [comment]
Fixed by PR #33.
