### ISSUE TITLE
Implement addShutdownHook for graceful shutdown on SIGTERM

### ISSUE THREAD

**Issue by akara** [paypal/squbs#202]
A shutdown is normally signalled by sending `Unicomplex` a `GracefulStop`. But we want to achieve the same clean shutdown if the JVM receives a SIGTERM. This is done by implementing `addShutdownHook` and not let it terminate until everything else has terminated.

Note that the shutdown hook is also called last thing on JVM termination with a `GracefulStop`. So it
needs to check if the `Unicomplex` or the `ActorSystem` is already gone (shutdown by the `GracefulStop` message). In that case the shutdown hook needs to be dormant and not have any other side effects, not send any `GracefulStop` again.

**Comment by anilgursel** [comment]
We should also add a configuration to delay shutdown.
