### ISSUE TITLE
Akka Http Route Actor should be part of flow

### ISSUE THREAD

**Issue by anilgursel** [paypal/squbs#290]
Currently, the `Route` actor is a singleton per route.  This might be a bottleneck if serialization/deserialization is CPU intensive.  We should rather make it part of the flow and let Akka Http control the underlying actors.

There can still be a Route actor at the cube level to provide the context.

**Comment by akara** [comment]
Fixed by #299. With the Spray removal we made the `RouteDefinition` expose the `Route that became baked into the `Flow`
