### ISSUE TITLE
Implement admin console cube

### ISSUE THREAD

**Issue by akara** [paypal/squbs#31]
This should expose system stats as well as JMX MBeans. Console could consist of well documented REST APIs so users can build and/or integrate with their own UI.

**Comment by kuanghao** [comment]
admin console is a very useful tool which could contain:

1. System information (e.g. server start time/metrics, CPU/Memory/Thread Usage)
2. JMX Beans (e.g. Squbs Cube metrics, httpClient metrics)
3. Hook for application to register info (e.g. Build Info, Package Info)
