### ISSUE TITLE
EndpointResolver chain does not resolve URL

### ISSUE THREAD

**Issue by akara** [paypal/squbs#342]
When using `ClientFlow` not passing a name, but a whole base URL, the `ClientFlow` should try to resolve it as name, and last check whether it is a URL and resolve that instead of giving up.

**Comment by anilgursel** [comment]
Yes.  But, not sure if it should be enabled by default, or that we should register it in the templates by default.

**Comment by anilgursel** [comment]
How should we register it?

- Should it be pre-registered by default in the chain? Being the default last one?
- Or it should not have any difference than any other resolver and should be registered at the template level in the extensions?

**Comment by anilgursel** [comment]
Also, consider adding DefaultEndpointResolver that resolves baseUrl from application.conf and ssl from there as well, or even merge it with SimpleEndpointResolver.
