### ISSUE TITLE
CustomTestKit should detect resources like SimpleTestKit

### ISSUE THREAD

**Issue by akara** [paypal/squbs#369]
Detecting resources from `src/main/resources` as well as its current `src/test/resources` would allow for full replacement of SimpleTestKit which auto-detects `squbs-meta.conf` from `src/main/resources`.

We should not make `withClassPath` true by default as not to have multiple test cases conflicting by over-scanning by default.

**Comment by anilgursel** [comment]
If we automatically scan `src/main/resources`; we also need to make sure that we can override anything configuration in it.

**Comment by akara** [comment]
Can you please elaborate more?

**Comment by anilgursel** [comment]
For instance, if there is some resource defined in `src/main/rsource/squbs-meta.conf`; and in a test, we do not want that to be enabled or set the path to some other route.

**Comment by anilgursel** [comment]
We should also assess the its cost to test execution time.  I would not expect much; but, something to keep in mind.

**Comment by akara** [comment]
Fixed, with issue #380 created to deal with config.
