### ISSUE TITLE
Loading components should catch `Throwable`, not `Exception`

### ISSUE THREAD

**Issue by akara** [paypal/squbs#385]
Otherwise loading a bad component may cause inadequate logging of the problem. The issue at hand is a component that gets loaded throws a `NoClassDefFoundError` because it was compiled for an older version of squbs and referencing a class that has since moved. At this time, the logs are swallowed and we won't know which component is the offending one until we debug.

**Comment by thefourtheye** [comment]
> should catch `Throwable`, not `Exception`

I am inclined to think catching with `scala.util.control.NonFatal` would be better than catching `Throwable`s. [Why You Should Never Catch Throwable In Scala](https://www.sumologic.com/blog-code/why-you-should-never-catch-throwable-in-scala/)

**Comment by akara** [comment]
Thanks @thefourtheye definitely agree!
