### ISSUE TITLE
refactor readConfigs(file) in UnicomplexBoot

### ISSUE THREAD

**Issue by thefourtheye** [paypal/squbs#388]
1. The `readConfigs` function which reads from jar file or a directory, defines two functions, based on the type of file passed as input (jar or directory). That can be refactored into two private functions.

2. The current file being processed is modified in both the functions mentioned in the previous point. We could reduce the footprint of that `var` variable by modifying it only before calling the refactored functions.

3. The code actually is written in a little imperative style. We could refactor it with the functional goodies of Scala.

**Comment by anilgursel** [comment]
Just marking it as "fixed".  We'll close it at the end of the sprint.
