### ISSUE TITLE
Issue with Persistent Buffer's time window based auto cleanup

### ISSUE THREAD

**Issue by SarathChandran** [paypal/squbs#401]
- queue's roll cycles based on `filename` cleanup causes issues with time window shifts back 0th hour.

- For example, when queue files with name series 20,21,..23 validated for cleanup and outport's min complete on 23rd hour then files prior to 23, that is, 20..22 are taken for deletion.  

- But (Issue scenario) - when 1st hour data is processed, the data files prior to it 23rd in case of hourly cycle `does not` get deleted.

- The logic of using file name's numbers to delete the file is the problem. https://github.com/paypal/squbs/blob/master/squbs-pattern/src/main/scala/org/squbs/pattern/stream/PersistentQueue.scala#L193

- Proposed Solution:
Instead of filename comprision, file's lastModifiedTime can be taken for comparision, which will allow deletion of old files without being caught due to naming issues.

![queuedata-cleanup](https://cloud.githubusercontent.com/assets/4623218/22852105/7bc569d0-f05b-11e6-8c91-ec570dd98957.png)

**Comment by anilgursel** [comment]
Discussion on Gitter https://gitter.im/paypal/squbs?at=589caa2b872fc8ce62146867
