### ISSUE TITLE
GraphStage for capturing demand and supply metrics

### ISSUE THREAD

**Issue by anilgursel** [paypal/squbs#464]

**Comment by sebady** [comment]
Adding some more detail:

This stage (`DemandSupplyFlow'?) is a linear `GraphStage` that when joined with a client's `Flow`s is used to capture (downstream) demand and (upstream) supply metrics for backpressure visibility.

This stage will capture and expose (via a dropwiz counters) the number of elements flowed from upstream and pushed downstream.
