### ISSUE TITLE
Drain response entity when a timeout happens

### ISSUE THREAD

**Issue by anilgursel** [paypal/squbs#487]
When a timeout happens, the `TimeoutBidi` stage sends a `Failure` to downstream and drops the actual response when received (after timeout period).  However, it should also allow a function to be passed for what to do when the response is received after the timeout.  For instance, for HTTP use cases, the response entity needs to be drained.  

Thanks @talst for reporting it https://gitter.im/paypal/squbs?at=597c5fc5329651f46ed1dc5a.

The timeout stage can be found at https://squbs.readthedocs.io/en/latest/flow-timeout/

**Comment by talst** [comment]
I've created a suggestion to add this functionality:  https://github.com/paypal/squbs/pull/488
