### ISSUE TITLE
support tracing via opentracing

### ISSUE THREAD

**Issue by sebady** [paypal/squbs#499]
Support trace using opentrace API
http://opentracing.io/documentation/pages/api/index

Should support pluggable trace "backends":
Jaeger - https://github.com/uber/jaeger
Zipkin - https://github.com/openzipkin/zipkin

Resources:
https://eng.uber.com/distributed-tracing/
https://dev.lightbend.com/blog/2017-05-08-cinnamon-2-4-with-opentracing-integration/index.html
http://www.hawkular.org/hawkular-apm/

**Comment by FisterDotOrg** [comment]
Thank you, @akara @anilgursel @jeffharrell @az-qbradley @sebady!

**Comment by FisterDotOrg** [comment]
Hi @akara ,

How’s OpenTracing support going?

Any ETA for 1.0.0 ( https://github.com/paypal/squbs/milestone/5 ) that you mentioned would have OpenTracing support?

**Comment by sebady** [comment]
The OpenTracing java special agent akka-http instrumentation plugin (see [here](https://github.com/opentracing-contrib/java-specialagent#61-instrumentation-plugins) largely makes this issue superfluous.
