### ISSUE TITLE
Bottles sample does not work on master branch

### ISSUE THREAD

**Issue by akara** [paypal/squbs#508]
This is likely a result of the Akka and Scala upgrade.

**Comment by crankydillob** [comment]
Is this the problem?

```
[error] /home/samuel/work/squbs/samples/bottles/bottlesvc/src/main/scala/org/squbs/bottlesvc/BottleSvc.scala:41: To compile XML syntax, the scala.xml package must be on the classpath.
[error] Please see https://github.com/scala/scala-xml for details.
[error]             <html>
[error]             ^
[error] one error found
[error] (bottlesvc/compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed Dec 23, 2017 8:28:44 AM
```

**Comment by akara** [comment]
This particular issue may be fixed by including scala-xml dependency for this project.

**Comment by ingared8** [comment]
Does any have a fix for this issue?  I'm trying to get to speed but got stuck here.

**Comment by anilgursel** [comment]
Sorry, not yet 😞  We have been working hard on getting other 0.10 release items.  I will address this one soon.

**Comment by akara** [comment]
@ingared These samples are pretty obsolete by now and we're even considering removing them. Perhaps starting from the application template and use that as a vehicle may be a better idea.

**Comment by anilgursel** [comment]
We will delete the bottles sample.  Please create a sample app linked from https://squbs.readthedocs.io/en/latest/#getting-started.
