### ISSUE TITLE
High CPU usage with Circuit Breaker combined with ClientFlow

### ISSUE THREAD

**Issue by vertexclique** [paypal/squbs#519]
There is a huge CPU usage with `CircuitBreaker` inside `ClientFlow`. Flow is trying to get elements but `NoSuchElementException` arises and wraps it to `None` and empty queue dequeuing allocates high CPU usage.

With configuration of:

```hocon
circuit-breaker {
  call-timeout = 5s
  reset-timeout = 10s
  max-failures = 5
  max-reset-timeout = 20s
}
```

and single instance of circuit breaker which is created with:
```scala
  val circuitBreakerName = s"circuit-breaker"

  val circuitBreakerState: CircuitBreakerState =
    AtomicCircuitBreakerState(
      name = circuitBreakerName,
      maxFailures = circuitBreakerConfig.maxFailures,
      callTimeout = circuitBreakerConfig.callTimeout,
      resetTimeout = circuitBreakerConfig.resetTimeout,
      maxResetTimeout = circuitBreakerConfig.maxResetTimeout
    )

  val cbSettings: CircuitBreakerSettings[HttpRequest, HttpResponse, Rewarding] =
    CircuitBreakerSettings[HttpRequest, HttpResponse, Rewarding](circuitBreakerState)
      .withFailureDecider(failureDecider)
      .withFallback(failureFallback)

  private def failureDecider(tryHttpResponse: Try[HttpResponse]): Boolean =
    tryHttpResponse.isFailure || tryHttpResponse.get.status.isFailure

  private def failureFallback(request: HttpRequest): Try[HttpResponse] = {
    val uri = request.uri.toString()
    val cbFailureBody = s"Failing fast after ${circuitBreakerConfig.maxFailures} attempts to $uri"

    logger.info(s"Circuit Breaker Activated for following url: $uri")

    Success(HttpResponse(status = StatusCodes.ServiceUnavailable, entity = HttpEntity(cbFailureBody)))
  }
```

and `ClientFlow` was initialized like:
```scala
    ClientFlow[Context](
      baseUrl,
      connectionContext = getSSLConnectionContext(scheme),
      circuitBreakerSettings = Some(circuitBreakerStorage.cbSettings)
    )
```

Here is the CPU sample showcase:
![screen shot 2017-09-26 at 14 26 41](https://user-images.githubusercontent.com/578559/30860626-120086e0-a2c8-11e7-990f-2b8463c912ea.png)

Also graphs:
![screen shot 2017-09-26 at 14 37 54](https://user-images.githubusercontent.com/578559/30860702-5579ce72-a2c8-11e7-983d-19ebbb9b3c5c.png)

**Comment by akara** [comment]
Thanks for reporting the issue in great detail. Yes, it looks like a bug in the circuit breaker.

**Comment by sebady** [comment]
@vertexclique Thank you for reporting this issue.  Can you please confirm that this issue is now fixed?

**Comment by sebady** [comment]
@vertexclique We believe this issue is now resolved.   Please reopen issue if you still see this problem.

**Comment by vertexclique** [comment]
@sebady Sorry, I don't know the current state of our project, just because I left it. So I think it is working as expected right now. Thanks.
