### ISSUE TITLE
Move sample apps to sbt docker 1.5.0

### ISSUE THREAD

**Issue by akara** [paypal/squbs#528]
From @eleduardo ... The sample apps are using sbt docker 1.4.0 which has a bug when building a docker image on the mac with the latest version... it seems that the problem is that the version of the daemon is now 17.09.0-ce-mac35 which confuses that version of the docker plugin. Moving to sbt docker 1.5.0 fixed the issue.

**Comment by sebady** [comment]
This should now be resolved with recent g8 template update
