### ISSUE TITLE
Fix search for documents on ReadTheDocs

### ISSUE THREAD

**Issue by sebady** [paypal/squbs#534]
To get search working on our readthedocs portal we need to setup an elastic search instance: 
http://docs.readthedocs.io/en/latest/install.html

**Comment by anilgursel** [comment]
We should not need to setup one, it is already there.  I believe the problem is about mkdocs and readthedocs integration.  If we move to `.rst`, the search should work fine.  I remember seeing bugs reported against readthedocs about the search.  I will add the links here.

**Comment by anilgursel** [comment]
It looks like the search is fixed already.
