### ISSUE TITLE
ActorRegistry never finishes initializing if there is no `squbs-actors` defined

### ISSUE THREAD

**Issue by akara** [paypal/squbs#536]
When testing with https://github.com/akara/echodelaysvc, if ActorRegistry is in the dependency list, the service never fully initializes. ActorRegistry never gets done initializing.

**Comment by anilgursel** [comment]
It looks like it does not initialize successfully when there is no `squbs-actors` defined in the classpath.  Please see `ActorRegistry.scala`:

```scala
  def startupReceive: Receive = {
    case ActorIdentity(cubeActorInfo : CubeActorInfo, Some(actor))=>
      registry += actor -> cubeActorInfo.messageTypeList
      register(new ActorRegistryBean(actor) , objName(actor))
      context.watch(actor)
      cubeCount -= 1
      if (cubeCount <= 0) {
        context.parent ! Initialized(Success(None))
        context.unbecome()
      }
    case _ => stash()
  }
```

As seen above, once all well-known actors are registered, `Initialized` message is sent; however, if there is no well-known actors, then the code would never reach the above section:

```scala
  def receive = {
    case StartActorRegister(cubeActorInfoList, timeout) =>
      register(new ActorRegistryConfigBean(timeout, context), prefix + configBean )

      cubeCount = cubeActorInfoList.size
      cubeActorInfoList.foreach { cubeActorInfo=>
        context.actorSelection(cubeActorInfo.actorPath) ! Identify(cubeActorInfo)
      }
```

Working on a fix now..
