### ISSUE TITLE
Default `ExceptionHandler` should be used if one not provided

### ISSUE THREAD

**Issue by anilgursel** [paypal/squbs#560]
Please see https://doc.akka.io/docs/akka-http/current/routing-dsl/exception-handling.html#default-exception-handler:

> A default ExceptionHandler is used if no custom instance is provided.

> It will handle every NonFatal throwable, write its stack trace and complete the request with InternalServerError (500) status code.

However, squbs does not handle it by default, please see https://github.com/paypal/squbs/blob/RELEASE-0.9.2/squbs-unicomplex/src/main/scala/org/squbs/unicomplex/ServiceRegistry.scala#L233.

**Comment by akara** [comment]
Need to set `ExceptionHandler` to `null` instead if none is defined. This will be converted to `ExceptionHandler.default(settings)` when the `ExceptionHandler.seal(handler)` is called. Please see: https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala#L61 for how this is done.
