### ISSUE TITLE
Please ensure code coverage and correct headers for org.squbs.httpclient.japi

### ISSUE THREAD

**Issue by akara** [paypal/squbs#66]
Many files don't have the headers. Also, code coverage is low. Can you please beef this up?

**Comment by tutufool** [comment]
I'm working on the test of squbs-pipeline, and will take this as well.
Btw, what's the coverage criteria? still 85% or 90%?

**Comment by akara** [comment]
85% is a pass. I try to achieve 100% on all new features.
