### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by sebady** [paypal/squbs#741]
Travis builds seems to be failing intermittently now with: 

"The job exceeded the maximum log length, and has been terminated."

Attempting to fix by reducing the overall console output during builds.

**Comment by akara** [comment]
I'll work on this on the coming weekends as part of removing the `Agent`s from code.

**Comment by akara** [comment]
As we have moved to GitHub actions, this issue is no longer needed. @sebady, can you please close?
