### ISSUE TITLE
Give a readable actor name to ServiceActor when a proxy exists

### ISSUE THREAD

**Issue by keshin** [paypal/squbs#76]
Currently the actor name would be assigned to the ProxyActor if a processor exists, considering if we can give an name to the service actor in case of actor selection

https://github.com/paypal/squbs/blob/master/squbs-unicomplex/src/main/scala/org/squbs/unicomplex/Unicomplex.scala#L621

```scala
        proxyName.fold(pipelineManager.default) {
          case "" => None
          case other => pipelineManager.getProcessor(other)
        } match {
          case None =>
            val hostActor = context.actorOf(props, name) // disable proxy
            (hostActor, SimpleActor(hostActor))
          case Some(proc) =>
            val hostActor = context.actorOf(props)
            (hostActor, ProxiedActor(context.actorOf(Props(classOf[CubeProxyActor], proc, hostActor), name)))
        }
```

A problem we need to consider is, what the actor names should be for the ServiceActor and ProxiedActor

**Comment by akara** [comment]
Considering fixing this for 0.7.1. @keshin please let me know of any concerns.
